### ISSUE TITLE
Proposal: Optional input parameter Low-Frequency resistance

### ISSUE THREAD

**Issue by StefanPofahl** [MaximeVH/EquivalentCircuits.jl#22]
Hi Maxime,

what about adding a punishment in the quality function for the difference between the measured low-frequency resistance and and the current result for the sum of the resistances?
Let's assume you have:
R1-L2-[R3,P4]-[R5,P6] 

then the low frequency resistance should equal to the sum: R_low_frequency = R1+R3+R5

The low frequency should be similar to the resistance that can be calculated according to the 
slope of the polarization curve.

And for this optional element in the quality function there should be also included a weighting factor.

What do you think?

Regards,

Stefan

**Comment by MaximeVH** [comment]
Hi Stefan,

This idea is useful and makes sense for the category of circuits to which your example belongs. However, not all circuit configurations will have this property. As I'd like to keep the functions in this package as general as possible (and not specific to a single subcategory), I think this would be more useful as a separate script with a redefinition of the objective function rather than a modification to the package as a whole.

Regards,

Maxime

**Comment by StefanPofahl** [comment]
Hi Maxime,

yes an example would be nice. :-) 

Regards,

Stefan

P.S.:
Also in other packages you have predefined standard equivalent circuits, 
but I agree, that a generic approach is often the best choice :-)

**Comment by StefanPofahl** [comment]
Cool :-)
