### ISSUE TITLE
Non-deterministic behavior

### ISSUE THREAD

**Issue by klaff** [MaximeVH/EquivalentCircuits.jl#26]
Hi, I am trying out EquivalentCircuits. I created a circuit of configuration `[R1,C2]-[R3,C4]-R5` and created dummy (ideal) impedance values.

If I pass those to `parameteroptimisation` with the circuit string, it generates correct values.

If I use `circuit_evaluation` and pass in `terminals = "RC"`, it sometimes gets close `[C1,R2]-[C3,R4]` (and the dropping of the `R5` is excusable due to it's relatively small value in the original model) but if I repeat the execution it might fail with `Algorithm did not converge`. In all cases I get a series of `Initial position cannot be on the boundary of the box. Moving elements to the interior.
Element indices affected: [4]` prints (although with varying indices).

I can share dummy values and test script if they would be helpful.

Also, is there a preferred forum for questions other than creating issues here?  Thanks!

**Comment by MaximeVH** [comment]
Hi, Are you using the newest version of the package? The superfluous warnings should be removed by now. Due to the `circuit_evolution` function being dependent on an evolutionary algorithm, it is not guaranteed to converge every time. However, within a few months, I will be releasing a new and improved version of the algorithm, using some new developments in evolutionary algorithms.
